/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import projeccct.Database;

/**
 *
 * @author sameh
 */
public class Flight extends javax.swing.JFrame {
    int counter = 1 ;
    private String username ;
    public Flight(String username) throws SQLException {
        initComponents();
        this.username = username ;
        Database database = new Database();
        /*List list = new ArrayList();
        list.add(6);
        list.add(6);
        list.add("Cairo , Egypt");
        list.add("Zagreb , croatia");
        list.add("9:00 AM");
        list.add("18/ 12 SUN");
        list.add("26000 EGP");
        database.addRow("flight", list);*/
        
        
        JScrollPane jScrollPane = new JScrollPane();
        gatheringInformationToCreatePanel(database.retrieveFlight());
        
    }

    void gatheringInformationToCreatePanel(ArrayList <Model.Flight> fligth){
        for(int i = 0 ; i < fligth.size() ; i++){
            createPanel(fligth.get(i) , i);
        }
    }
    
    void createPanel(Model.Flight flight , int i){
        Container c = getContentPane();
        
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(8, 8));
        
        panel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 10));
        
        JLabel D_To = new JLabel(flight.getD_To());
        D_To.setFont(new Font("Verdana", Font.PLAIN, 12));
        panel.add(D_To);
        
        JLabel space = new JLabel("  ");
        panel.add(space);
        
        
        JLabel S_from = new JLabel(flight.getS_From());
        S_from.setFont(new Font("Verdana", Font.PLAIN, 12));
        panel.add(S_from);
        
        JLabel space1 = new JLabel("  ");
        panel.add(space1);
        
        JLabel day = new JLabel(flight.getDay());
        day.setFont(new Font("Verdana", Font.PLAIN, 12));
        panel.add(day);
        
        JLabel time = new JLabel(flight.getTime());
        time.setFont(new Font("Verdana", Font.PLAIN, 12));
        panel.add(time);
        
        JLabel space3 = new JLabel("  ");
        panel.add(space3);
        
        JLabel price = new JLabel(flight.getPrice());
        price.setFont(new Font("Verdana", Font.CENTER_BASELINE, 12));
        panel.add(price);
            
        panel.setBackground(Color.CYAN);
        int HEIGHT = 10 ;
        int width  = 10 + i*145 + 20*i ;
        
        if( i != 0 && i %5 == 0){
            HEIGHT = 10 + 170 * counter  ;
            counter++;
            width = 10 ;
        }
        
        System.out.println( width + " , " + HEIGHT);
        
        panel.setBounds( width , HEIGHT , 160 , 165 );
        
        c.add(panel);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(837, 361));
        setMinimumSize(new java.awt.Dimension(837, 361));
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(572, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new MAIN(username).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Flight("").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Flight.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}


/*
Database database = new Database();
        List list = new ArrayList();
        list.add(3);
        list.add(3);
        list.add("Cairo , Egypt");
        list.add("Madrid , spain");
        list.add("4:00 AM");
        list.add("18/ 12 SUN");
        list.add("13000 EGP");
        database.addRow("flight", list);
*/